[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
send_usd = "8SkhDK31jrk7hCB7SLpvmCe4UdfhvCgRQkS197YxYTX1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/hugongra/.config/solana/id.json" 

[workspace]
members = ["program"]

[scripts]
test = "cargo test-sbf"
